project_id = "rrcbxpgbgahjrdizktrt"

[functions.send-request-notification]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.resend-invite]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.send-test-email]
verify_jwt = false
